### ISSUE TITLE
Check NullPointerException for 6zcz and 6zxn

### ISSUE THREAD

**Issue by Domino2357** [scenerygraphics/scenery-proteins#28]
[ERROR] testLotsOfProteins(graphics.scenery.tests.unit.RibbonDiagramTests)  Time elapsed: 37.178 s  <<< ERROR!
java.lang.NullPointerException
	at graphics.scenery.tests.unit.RibbonDiagramTests.testLotsOfProteins(RibbonDiagramTests.kt:234)
[ERROR] numberSubProteinsTest(graphics.scenery.tests.unit.RibbonDiagramTests)  Time elapsed: 20.491 s  <<< ERROR!
java.lang.NullPointerException
	at graphics.scenery.tests.unit.RibbonDiagramTests.numberSubProteinsTest(RibbonDiagramTests.kt:77)

(AppVeyor on the Pull-Request for Ribbon Branch to Scenery; https://github.com/scenerygraphics/scenery/commit/fce29c2824e2c9a97d91cbe10110963b082cb60c)

**Comment by Domino2357** [comment]
Maybe this is due to having the same entry twice in one class?

**Comment by Domino2357** [comment]
> Maybe this is due to having the same entry twice in one class?

Nope

**Comment by Domino2357** [comment]
I will close this issue because all other testing platforms run smoothly with this entry and also the visualization is flawless.
